### ISSUE TITLE
missing samples

### ISSUE THREAD

**Issue by smb20200615** [CSB5/AD-caregiver-manuscript#1]
Hello,

Some of the samples are missing (eg. WMB1563,WMB1566,WMB1571,etc)

When will these runs be available?

Best wishes,

**Comment by Chiamh** [comment]
Hello,

The WMB* samples are now available. Thanks!

**Comment by smb20200615** [comment]
Thank you. Where are they available now? Also is there metadata available for them too? I only see metadata for 52 of the isolates

**Comment by Chiamh** [comment]
Hello, the WMB* isolates can be downloaded from ENA under the same project ID: https://www.ebi.ac.uk/ena/browser/view/PRJEB42399?show=reads  (scroll to last page probably). Since they were recently submitted, it would take awhile before they are also available on SRA. Sorry - I'd assumed it would be faster. There is metadata for 58 sequenced isolates analyzed in the corrected manuscript in metadata/manuscript_isolates_metadata.tsv. I have updated the metadata file for 55 isolates that passed QC in metadata/passQC_isolates_metadata.tsv. Also see scripts/fig4a_isolates_analysis.Rmd for details about the QC. The manuscript should be out in JACI this month to give more context.
